server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  freemarker:
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
    charset: UTF-8
  application:
    name: mobile
  redis:
    database: 1
    port: 6379
    host: 172.16.202.131
    password: 123456

